import { Button } from '@mui/material';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="mx-auto flex min-h-screen flex-col py-10 sm:container">
                <div className="items-left flex justify-between py-9">
                    <h1 className="text-3xl font-bold tracking-tight sm:text-left sm:text-3xl">
                        My all Notes
                    </h1>
                    <div>
                        <Link
                            className="inline-block rounded-lg bg-green-600 px-4 py-1.5 text-base font-semibold leading-7 text-white shadow-sm ring-1 ring-green-600 hover:bg-green-700 hover:ring-green-700"
                            href="/note/add"
                        >
                            Add a note
                        </Link>
                    </div>
                </div>
                <div className="mt-5">
                    <Link href="/signin">
                        <Button variant="contained" className="bg-green-300">
                            signIn
                        </Button>
                    </Link>
                </div>
            </main>
        </>
    );
};

export default Home;
